---
abstract: 'Load (remote) URIs into config'
author:
  - 'J. Shirley, C<< <jshirley at gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-ConfigLoader-Remote
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Plugin::ConfigLoader: 0
  File::Fetch: 0
  MRO::Compat: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
