--- 
abstract: Load (remote) URIs into config
author: J. Shirley, C<< <jshirley at gmail.com> >>
distribution_type: module
generated_by: Module::Install version 0.670
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-ConfigLoader-Remote
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Plugin::ConfigLoader: 0
  File::Fetch: 0
version: 0.01
